# Generated by Django 4.1.6 on 2023-02-13 17:39

from django.conf import settings
from django.db import migrations, models
import memeta_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField()),
                ('back', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=models.SET(memeta_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
