# Generated by Django 4.1.6 on 2023-02-15 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import memeta_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('finish_time', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeta_app.card')),
                ('user', models.ForeignKey(on_delete=models.SET(memeta_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
