# Generated by Django 4.1.6 on 2023-02-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0002_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='try',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
