# Generated by Django 4.1.6 on 2023-02-15 18:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0003_alter_try_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
