# Generated by Django 4.1.6 on 2023-02-15 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import memeta_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0004_alter_card_back_alter_card_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='try',
            name='perc_corr_apriori',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='try',
            name='perc_corr_expost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='try',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tries', to='memeta_app.card'),
        ),
        migrations.AlterField(
            model_name='try',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(memeta_app.models.get_sentinel_user), related_name='tries', to=settings.AUTH_USER_MODEL),
        ),
    ]
