# Generated by Django 4.1.6 on 2023-02-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0005_try_perc_corr_apriori_try_perc_corr_expost_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try',
        ),
    ]
