# Generated by Django 4.1.6 on 2023-02-16 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0006_delete_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='exluded_by',
            field=models.ManyToManyField(related_name='excluded_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
