# Generated by Django 4.1.6 on 2023-02-17 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0011_remove_session_start_date_session_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='excluded_by',
        ),
        migrations.AddField(
            model_name='card',
            name='appreciated_by',
            field=models.ManyToManyField(related_name='appreciated_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='card',
            name='sorted_out_by',
            field=models.ManyToManyField(related_name='sorted_out_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
