# Generated by Django 4.1.6 on 2023-02-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0012_remove_card_excluded_by_card_appreciated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='subject',
            field=models.CharField(default='unbekannt', max_length=255),
            preserve_default=False,
        ),
    ]
