# Generated by Django 4.1.6 on 2023-02-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0013_subject_card_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='subject_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='memeta_app.subject'),
        ),
    ]
