# Generated by Django 4.1.6 on 2023-02-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0014_card_subject_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='subject',
        ),
        migrations.AlterField(
            model_name='card',
            name='subject_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='memeta_app.subject'),
        ),
    ]
