# Generated by Django 4.1.6 on 2023-02-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0015_remove_card_subject_alter_card_subject_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='subject_ref',
            new_name='subject',
        ),
    ]
