# Generated by Django 4.1.6 on 2023-02-18 11:25

from django.conf import settings
from django.db import migrations, models
import memeta_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0016_rename_subject_ref_card_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('cards', models.ManyToManyField(related_name='featured_in', to='memeta_app.card')),
                ('learner', models.ForeignKey(on_delete=models.SET(memeta_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
