# Generated by Django 4.1.6 on 2023-02-18 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('memeta_app', '0017_set_delete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(related_name='studied_by', to='memeta_app.subject')),
            ],
        ),
    ]
