# Generated by Django 4.1.6 on 2023-02-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0018_preferences'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Set',
        ),
    ]
