# Generated by Django 4.1.6 on 2023-02-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0019_delete_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='subject',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='subjects',
            new_name='courses',
        ),
        migrations.RenameModel(
            old_name='Subject',
            new_name='Course',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memeta_app.course')),
            ],
        ),
    ]
