# Generated by Django 4.1.6 on 2023-02-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0021_card_event_alter_card_appreciated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='event',
        ),
        migrations.AlterField(
            model_name='card',
            name='course',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='memeta_app.course'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
