# Generated by Django 4.1.6 on 2023-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0023_alter_card_course_session_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='cards',
            field=models.ManyToManyField(related_name='featured_in', to='memeta_app.card'),
        ),
    ]
