# Generated by Django 4.1.6 on 2023-02-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0024_alter_session_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rep',
            name='session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='session',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.AddField(
            model_name='rep',
            name='knew_judged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rep',
            name='know_predicted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='reps',
            field=models.ManyToManyField(related_name='constituting', to='memeta_app.rep'),
        ),
    ]
