# Generated by Django 4.1.6 on 2023-02-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0025_remove_rep_session_remove_session_cards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rep',
            old_name='knew_judged',
            new_name='i_knew',
        ),
        migrations.RenameField(
            model_name='rep',
            old_name='know_predicted',
            new_name='i_know',
        ),
    ]
