# Generated by Django 4.1.6 on 2023-02-23 17:09

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0026_rename_knew_judged_rep_i_knew_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='reps',
        ),
        migrations.AddField(
            model_name='session',
            name='string_of_list_of_card_pks',
            field=models.TextField(null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='rep',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
