# Generated by Django 4.1.6 on 2023-02-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0030_alter_session_card_pk_list_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='next_list_position',
            field=models.SmallIntegerField(default=0),
        ),
    ]
