# Generated by Django 4.1.6 on 2023-02-24 21:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0031_session_next_list_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 24, 22, 4, 0, 491070)),
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_pk_list_string', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(to='memeta_app.course')),
                ('reps', models.ManyToManyField(to='memeta_app.rep')),
                ('sorted_out_cards', models.ManyToManyField(to='memeta_app.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
