# Generated by Django 4.1.6 on 2023-02-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0033_alter_session_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reps',
            field=models.ManyToManyField(to='memeta_app.rep'),
        ),
    ]
