# Generated by Django 4.1.6 on 2023-02-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0035_rep_card_correct_alter_session_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='i_understand',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
