# Generated by Django 4.1.6 on 2023-02-27 12:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import memeta_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0036_rep_i_understand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='memeta_app.course')),
                ('creator', models.ForeignKey(on_delete=models.SET(memeta_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('appreciated_by', models.ManyToManyField(blank=True, related_name='appreciated', to=settings.AUTH_USER_MODEL)),
                ('back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='back_for', to='memeta_app.cardfront')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='memeta_app.course')),
                ('creator', models.ForeignKey(on_delete=models.SET(memeta_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('front', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='front_for', to='memeta_app.cardfront')),
                ('sorted_out_by', models.ManyToManyField(blank=True, related_name='sorted_out', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='memeta_app.course')),
                ('creator', models.ForeignKey(on_delete=models.SET(memeta_app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
