# Generated by Django 4.1.6 on 2023-02-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0037_cardfront_compcard_cardback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compcard',
            name='back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='back_for', to='memeta_app.cardback'),
        ),
    ]
