# Generated by Django 4.1.6 on 2023-02-28 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0038_alter_compcard_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='appreciated_by',
            field=models.ManyToManyField(blank=True, related_name='appreciated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='back_for', to='memeta_app.cardback'),
        ),
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='front_for', to='memeta_app.cardfront'),
        ),
        migrations.AlterField(
            model_name='card',
            name='sorted_out_by',
            field=models.ManyToManyField(blank=True, related_name='sorted_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CompCard',
        ),
    ]
