# Generated by Django 4.1.6 on 2023-03-01 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0039_remove_card_creation_date_card_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='appreciated_by',
            field=models.ManyToManyField(blank=True, related_name='appreciated_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='sorted_out_by',
            field=models.ManyToManyField(blank=True, related_name='sorted_out_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
