# Generated by Django 4.1.6 on 2023-03-01 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0041_alter_cardback_course_alter_cardfront_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardback',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='memeta_app.course'),
        ),
        migrations.AlterField(
            model_name='cardfront',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='memeta_app.course'),
        ),
    ]
