# Generated by Django 4.1.6 on 2023-03-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0043_remove_cardback_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardfront',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='memeta_app.course'),
        ),
    ]
