# Generated by Django 4.1.6 on 2023-03-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0044_alter_cardfront_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rep',
            name='card_correct',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='i_understand',
        ),
        migrations.AlterField(
            model_name='rep',
            name='i_knew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rep',
            name='i_know',
            field=models.BooleanField(default=False),
        ),
    ]
