# Generated by Django 4.1.6 on 2023-03-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0046_rep_back_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='i_knew',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rep',
            name='i_know',
            field=models.BooleanField(),
        ),
    ]
