# Generated by Django 4.1.6 on 2023-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0047_alter_rep_i_knew_alter_rep_i_know'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='i_knew',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rep',
            name='i_know',
            field=models.BooleanField(default=False),
        ),
    ]
