# Generated by Django 4.1.6 on 2023-03-10 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0048_alter_rep_i_knew_alter_rep_i_know'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said_when', models.DateTimeField(auto_now_add=True)),
                ('when', models.DateTimeField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memeta_app.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
