# Generated by Django 4.1.6 on 2023-03-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0049_illknow'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='illknow',
            constraint=models.UniqueConstraint(fields=('user', 'card'), name='unique prognosis'),
        ),
    ]
