# Generated by Django 4.1.6 on 2023-03-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0050_illknow_unique prognosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='rep',
            name='honors_bet',
            field=models.BooleanField(default=False),
        ),
    ]
