# Generated by Django 4.1.6 on 2023-03-11 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memeta_app', '0051_rep_honors_bet'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonoredIllKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said_when', models.DateTimeField()),
                ('when', models.DateTimeField()),
                ('honored', models.DateTimeField(auto_now_add=True)),
                ('i_know', models.BooleanField()),
                ('i_knew', models.BooleanField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memeta_app.card')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memeta_app.rep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
