# Generated by Django 4.1.6 on 2023-03-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0052_honoredillknow'),
    ]

    operations = [
        migrations.AddField(
            model_name='honoredillknow',
            name='probable',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=4),
        ),
        migrations.AddField(
            model_name='illknow',
            name='probable',
            field=models.DecimalField(choices=[(0.01, 'min'), (25, 'low'), (50, 'medium'), (75, 'high'), (99.99, 'max')], decimal_places=2, default=99.99, max_digits=4),
        ),
    ]
