# Generated by Django 4.1.6 on 2023-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0053_honoredillknow_probable_illknow_probable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honoredillknow',
            name='probable',
            field=models.DecimalField(choices=[(0.01, '0.01%'), (25.0, '25%'), (50.0, '50%'), (75.0, '75%'), (99.99, '99.99%')], decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='illknow',
            name='probable',
            field=models.DecimalField(choices=[(0.01, '0.01%'), (25.0, '25%'), (50.0, '50%'), (75.0, '75%'), (99.99, '99.99%')], decimal_places=2, max_digits=4),
        ),
    ]
