# Generated by Django 4.1.6 on 2023-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0054_alter_honoredillknow_probable_alter_illknow_probable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honoredillknow',
            name='probable',
            field=models.DecimalField(choices=[(0, '0.01%'), (25, '25%'), (50, '50%'), (75, '75%'), (99, '99.99%')], decimal_places=2, max_digits=4),
        ),
    ]
