# Generated by Django 4.1.6 on 2023-03-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memeta_app', '0055_alter_honoredillknow_probable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honoredillknow',
            name='probable',
            field=models.SmallIntegerField(choices=[(1, '1%'), (25, '25%'), (50, '50%'), (75, '75%'), (99, '99%')], default=99),
        ),
        migrations.AlterField(
            model_name='illknow',
            name='probable',
            field=models.SmallIntegerField(choices=[(1, '1%'), (25, '25%'), (50, '50%'), (75, '75%'), (99, '99%')], default=99),
        ),
    ]
